apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-api
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: demo-api
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
          image: <docker-hub-account>/demo-api:v1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: demo-api-svc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: demo-api
